name: unit-test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  unit-test:
    name: Lint Build Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: cargo build --release --verbose
      - name: Run Lint and Test
        run: make
