name: unit-test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions: {}
jobs:
  unit-test:
    permissions:
      contents: read
    uses: muleyuck/github-actions/.github/workflows/ci-rust.yml@v1
